### PR TITLE
Add wireguard support

### PR DESCRIPTION
**Pull request by likeadragonmaid**
I have tested this and it works correctly.

### CODE REVIEW

**Comment by kdrag0n** [comment]
There are a few glaring issues with this:
 - You should not be committing the contents of `net/wireguard` into the Git repo. That is meant to be in .gitignore, with the importer script handling everything.
 - You stripped authorship from the importer commit. That commit is by zx2c4, but now it shows you being the author of it.
 - A quick skim shows that you have not imported Wireguard in `net/Makefile`.

**Comment by likeadragonmaid** [comment]
Okay, I will try again as you specified

**Comment by kdrag0n** [comment]
Why are you doing this? WireGuard support already exists in this kernel.

**Comment by likeadragonmaid** [comment]
I did this in an error.

**Pull request closed without merging**
